<h4><i style="color: #d9cd0f;" class="glyphicon glyphicon-info-sign"></i> Envie emails para pessoas que estao seguindo
    a instituicao</h4>
<hr>

<div class="col-sm-12">
<?php

echo $this->botoesHelper($this->botoesHelper);
echo  $this->grid;

$modal = new \Application\Helper\ModalHelper();
$modal->setId('modal_envia_email');
$modal->setTitle('Enviar Email');
//$modal->setContent('');
echo $modal->renderModal();

?>
</div>


