
<div class="login-box">
    <div class="login-logo">
        <a href="../../index2.html"><b>Sis</b>Doar</a>
    </div><!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Realize o Login</p>

        <?php echo $this->form(null, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL)->openTag($this->form); ?>
            <?php echo $this->formRow($this->form->get(\Application\Constants\UsuarioConst::FLD_IDENTITY)); ?>
            <?php echo $this->formRow($this->form->get(\Application\Constants\UsuarioConst::FLD_SENHA)); ?>

        <div class="row">
            <div class="col-xs-8">
                <div class="checkbox icheck">
                    <label>
                        <input type="checkbox"> Lembrar
                    </label>
                </div>
            </div><!-- /.col -->
            <div class="col-xs-4">
                <?php echo $this->formButton($this->form->get(\Application\Constants\UsuarioConst::FLD_ENTRAR)); ?>
            </div><!-- /.col -->
        </div>

        <div class="social-auth-links text-left">
            <!-- <p>- Ou -</p>
             <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Logar com o Facebook</a>
             <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Logar com o Google</a>
         </div><!-- /.social-auth-links -->

        <a href="#">Esqueci a senha</a><br>
        <a href="/usuario/incluir" class="text-center">Registrar</a>

    </div><!-- /.login-box-body -->
</div><!-- /.login-box -->


<?php echo $this->form()->closeTag(); ?>

<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        });
    });
</script>
