<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('id', 'validarAcessoForm');
$form->setAttribute('action', $this->url(\Application\Constants\RotasConst::VALIDAR_CHAVE_ACESSO));
$form->setAttribute('method', 'post');

?>

<div class="login-container">

    <div class="space-6"></div>

    <div class="position-relative">
        <div id="login-box" class="login-box visible no-border">
            <div class="widget-body">
                <div class="widget-main">

                    <!--<div class="widget-toolbox">-->

                    <div class="col-xs-12">
                        <h4 class="header blue lighter bigger">
                            <i class="ace-icon fa fa-unlock green"></i>
                            Primeiro Acesso do Usuário ao Perfil
                        </h4>

                        <div class="space-6"></div>

                        <fieldset>
                            <?php if (isset($status['type']) && $status['type'] == 'success') : ?>
                                <div
                                    class="alert alert-success"><?php echo \Application\Util\Mensagens::getMensagem('M03'); ?></div>
                                <hr/>
                            <?php elseif (isset($status['type']) && $status['type'] == 'error') : ?>
                                <div class="alert alert-danger">
                                    <?php echo $status['message']; ?></div>
                                <hr/>
                            <?php elseif (isset($status['type']) && $status['type'] == 'warning') : ?>
                                <div class="alert alert-warning">
                                    <?php echo $status['message']; ?>
                                </div>
                                <hr/>
                            <?php endif; ?>


                        </fieldset>
                        <?php echo $this->form(null, \FormBootstrap\Form\View\Helper\BootstrapForm::LAYOUT_HORIZONTAL)->openTag($form) ?>
                        <fieldset>
                            <br/>
                            <?php echo $this->formRow($form->get(\Application\Constants\UsuarioConst::FLD_IDENTITY)); ?>
                            <?php echo $this->formRow($form->get(\Application\Constants\UsuarioConst::FLD_SENHA)); ?>
                            <?php echo $this->formRow($form->get(\Application\Constants\UsuarioConst::FLD_CHAVE_ACESSO), array('labelClassSize' => 'col-sm-4', 'fieldClassSize' => 'col-sm-8')); ?>
                            <br/>

                            <div class="botoesacao">
                                <?php echo $this->formButton($form->get('btnCancelar')); ?>
                                <?php echo $this->formButton($form->get('btnConfirmar')); ?>
                            </div>
                        </fieldset>

                        <?php echo $this->form()->closeTag() ?>

                    </div>
                </div>
                <!-- /.widget-main -->
            </div>
            <!-- /.widget-body -->
        </div>
    </div>
</div>

<script>

    function cancelar(e) {
        window.location = $(e).data('href');
    }

</script>
