<?php $quantTransacoesPendentes = $this->transacoesPendentes ?>
<?php $quantdoacoesAtivas = $this->doacoes ?>
<?php $quantDoacoesFinanceiras = $this->doacoesFinanceiras ?>
<?php $seguidores = $this->relacao ?>

<div class="row">
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3><?php echo !is_null($quantdoacoesAtivas) ?  $quantdoacoesAtivas : 0 ?></h3>
                <p>Produtos/Serviços</p>
            </div>
            <div class="icon">
                <i class="ion ion-person-add"></i>
            </div>
            <a href="/produto" class="small-box-footer">Ver Mais <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div><!-- ./col -->

    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3><?php echo !is_null($quantTransacoesPendentes) ?  $quantTransacoesPendentes : 0 ?></h3>
                <p>Transações Pendentes</p>
            </div>
            <div class="icon">
                <i class="ion ion-bag"></i>
            </div>
            <a href="/transacao" class="small-box-footer">Ver Mais <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div><!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
            <div class="inner">
                <h3><?php echo $this->porcentagemTransacoes ?><sup style="font-size: 20px">%</sup></h3>
                <p>Transações Finalizadas</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a href="#" class="small-box-footer">Ver Mais <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div><!-- ./col -->

    <!--
    <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-red">
            <div class="inner">
                <h3><?php // echo !is_null($quantDoacoesFinanceiras) ? $quantDoacoesFinanceiras : 0 ?></h3>
                <p>Doações Financeiras Pendentes</p>
            </div>
            <div class="icon">
                <i class="ion ion-cash"></i>
            </div>
            <a href="/doacao-financeira" class="small-box-footer">Ver Mais<i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
     -->

    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-gray">
            <div class="inner" style="height: 100px">
                <h3></h3>
                <p>Relacionamentos</p>
            </div>
            <div class="icon">
                <i class="fa fa-users"></i>
            </div>
            <a href="/relacionamento" class="small-box-footer">Ver Mais<i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div><!-- ./col -->

</div><!-- /.row -->
<!-- Main row -->
<div class="row">


    <!-- right col (We are only adding the ID to make the widgets sortable)-->
    <section class="col-lg-5 connectedSortable">
            <!-- USERS LIST -->
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3 class="box-title">Seguidores</h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                    </div>
                </div><!-- /.box-header -->
                <div class="box-body no-padding">
                    <ul class="users-list clearfix">
                    <?php
                    /** @var \Sisdo\Entity\Relationship $seguidor */
                    foreach($seguidores as $seguidor){
                        echo <<<DOC
                        <li>
                            <img src="{$seguidor->getPersonUserId()->getPerson()->getPicture()}" alt="User Image">
                            <a class="users-list-name" href="/pessoa/pagina/{$seguidor->getPersonUserId()->getPerson()->getId()}">{$seguidor->getPersonUserId()->getPerson()->getName()}</a>
                            <span class="users-list-date">Today</span>
                        </li>
DOC;
                    }
                ?>
                </ul><!-- /.users-list -->
                </div><!-- /.box-body -->
                <div class="box-footer text-center">
                    <a href="/relacionamento" class="uppercase">Ver Todos</a>
                </div><!-- /.box-footer -->
            </div><!--/.box -->
    </section><!-- right col -->
</div><!-- /.row (main row) -->
