<?php
/** @var \Application\Entity\User $user */
$user = $this->usuarioLogado;
/** @var \Sisdo\Entity\Person $pessoa */
$pessoa = $user->getPerson();

?>


<!--
User Profile Sidebar by @keenthemes
A component of Metronic Theme - #1 Selling Bootstrap 3 Admin Theme in Themeforest: http://j.mp/metronictheme
Licensed under MIT
-->

    <div class="row profile">
        <div class="col-md-3">
            <div class="profile-sidebar">
                <!-- SIDEBAR USERPIC -->
                <div class="profile-userpic">
                    <img src="<?php echo $pessoa->getPicture() ?>" class="img-responsive" alt="">
                </div>
                <!-- END SIDEBAR USERPIC -->
                <!-- SIDEBAR USER TITLE -->
                <div class="profile-usertitle">
                    <div class="profile-usertitle-name">
                        <?php echo $pessoa->getName() ?>
                    </div>
                    <div class="profile-usertitle-job">
                        <?php echo $pessoa->getAboutMe() ?>
                    </div>
                </div>
                <!-- END SIDEBAR USER TITLE -->

                <!-- SIDEBAR MENU -->
                <div class="profile-usermenu">
                        <table class="table table-striped table-hover">
                            <tbody>
                            <tr>
                                <td style="width:60%;">Doacoes Pendentes:</td>
                                <td><span class="label label-danger">2</span></td>
                            </tr>
                            <tr>
                                <td>Ranking</td>
                                <td><i class="fa fa-star  fa-fw"></i><i
                                        class="fa fa-star  fa-fw"></i><i
                                        class="fa fa-star  fa-fw"></i><i
                                        class="fa fa-star  fa-fw"></i><i
                                        class="fa fa-star  fa-fw"></i></td>
                            </tr>
                            <tr>
                                <td>Membro desde</td>
                                <td> <?php echo $user->getDate()->format('d/m/Y') ?></td>
                            </tr>
                            </tbody>
                        </table>
                </div>
                <!-- END MENU -->
            </div>
        </div>
        <div class="col-md-9">
                <div class="panel">
                    <div class="panel-body-list">
                        <h3 class=""><i class="fa fa-users mgr-10"></i> Relacionamentos</h3>

                        <div>
                            <?php
                            $relacionamentos = $this->relacionamentos;

                            /** @var \Sisdo\Entity\Relationship $relacionamento */
                            foreach($relacionamentos as $relacionamento){
                                /** @var \Sisdo\Entity\Institution $instituicao */
                                $instituicao = $relacionamento->getInstitutionUserId()->getInstituicao();

                                echo <<<DOC
                                           <div class='col-sm-3'>
                                                <p>{$instituicao->getFancyName()}</p>
                                                <p>{$instituicao->getAbout()}</p>
                                           </div>
DOC;
                            }

                            ?>
                        </div>
                    </div>
            </div>
        </div>
    </div>
<br>
<br>







<script>

</script>