pessoa


<script src="//js.pusher.com/2.2/pusher.min.js" type="text/javascript"></script>
<script src="//code.jquery.com/jquery-2.1.3.min.js" type="text/javascript"></script>

<input class="create-notification" placeholder="Send a notification :)"></input>
<button class="submit-notification">Go!</button>

<div class="notification"></div>

<script>

    var pusher = new Pusher('c2a648e31b7233e57d83');

    var notificationsChannel = pusher.subscribe('notifications');

    notificationsChannel.bind('new_notification', function (notification) {
        var message = notification.message;
        console.log(message);
        $('div.notification').text(message);
    });

    var sendNotification = function () {

        // get the contents of the input
        var text = $('input.create-notification').val();

        // POST to our server
        $.post('/notificacao', {message: text}).success(function () {
            console.log('Notification sent!');
        });
    };

    $('button.submit-notification').on('click', sendNotification);

    /* var pusher = new Pusher('c2a648e31b7233e57d83');

     var notificationsChannel = pusher.subscribe('notifications');

     notificationsChannel.bind('new_notification', function(notification){
     var message = notification.message;
     $('div.notification').text(message);
     });
     */
    /* var pusher = new Pusher('c2a648e31b7233e57d83');

     var notificationsChannel = pusher.subscribe('notification');

     notificationsChannel.bind('new_notification', function(notification){
     var message = notification.message;
     console.log(notification);
     $('div.notification').text(message);
     });
     */

</script>

<!--<input class="create-notification" placeholder="Send a notification :)">
<button class="submit-notification">Go!</button>
--><!--
<script>
    var sendNotification = function(){

        // get the contents of the input
        var text = $('input.create-notification').val();

        // POST to our server
        $.post('/notificacao', {message: text}).success(function(json){
            console.log('Notification sent!');
            console.log(json);
        });
    };

    $('button.submit-notification').on('click', sendNotification);
</script>-->