pessoa


<script src="https://js.pusher.com/2.2/pusher.min.js"></script>
<script>

    /*
    // Enable pusher logging - don't include this in production
    Pusher.log = function(message) {
        if (window.console && window.console.log) {
            window.console.log(message);
        }
    };

    var pusher = new Pusher('c2a648e31b7233e57d83', {
        encrypted: true
    });
    var channel = pusher.subscribe('test_channel');
    channel.bind('my_event', function(data) {
        alert(data.message);
    });
    */
</script>
