<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')) ?>

<!-- bootstrap & fontawesome -->
<link rel="stylesheet" href="<?php echo $this->basePath('/css/bootstrap.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('/css/font-awesome.css?nome'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('/css/jquery-ui.css'); ?>"/>

<!-- text fonts -->
<link rel="stylesheet" href="<?php echo $this->basePath('/css/ace-fonts.css'); ?>"/>

<link rel="stylesheet" href="<?php echo $this->basePath('/css/jquery.dataTables.css'); ?>"/>
<link rel="stylesheet"
      href="<?php echo $this->basePath('/assets/datatable/extensions/ColVis/css/dataTables.colVis.min.css'); ?>"/>
<link rel="stylesheet"
      href="<?php echo $this->basePath('/assets/datatable/extensions/ColReorder/css/dataTables.colReorder.min.css'); ?>"/>
<link rel="stylesheet"
      href="<?php echo $this->basePath('/assets/datatable/extensions/TableTools/css/dataTables.tableTools.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('/assets/select2/select2.css'); ?>"/>
<!-- ace styles -->
<link rel="stylesheet" href="<?php echo $this->basePath('/css/ace.css'); ?>" class="ace-main-stylesheet"
      id="main-ace-style"/>

<!--[if lte IE 9]>
<link rel="stylesheet" href="<?php echo $this->basePath('/css/ace-part2.css'); ?>" class="ace-main-stylesheet"/>
<![endif]-->

<!--[if lte IE 9]>
<link rel="stylesheet" href="<?php echo $this->basePath('/css/ace-ie.css'); ?>"/>
<![endif]-->


<link rel="stylesheet" href="<?php echo $this->basePath('/css/cjf-templates.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('/css/cjf.css'); ?>"/>

<!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->

<!--[if lte IE 8]>
<script src="<?php echo $this->basePath('/js/html5shiv.js'); ?>"></script>
<script src="<?php echo $this->basePath('/js/respond.js'); ?>"></script>
<![endif]-->

<!--[if !IE]> -->
<script type="text/javascript">
    window.jQuery || document.write("<script src='<?php echo $this->basePath('/js/jquery.js'); ?>'>" + "<" + "/script>");
</script>

<!-- <![endif]-->

<!--[if IE]>
<script type="text/javascript">
    window.jQuery || document.write("<script src='<?php echo $this->basePath('/js/jquery1x.js'); ?>'>" + "<" + "/script>");
</script>
<![endif]-->
<script type="text/javascript">
    if ('ontouchstart' in document.documentElement) document.write("<script src='<?php echo $this->basePath('/js/jquery.mobile.custom.js'); ?>'>" + "<" + "/script>");
</script>
<script src="<?php echo $this->basePath('/js/bootstrap.js'); ?>"></script>

<!-- page specific plugin scripts -->

<!--[if lte IE 8]>
<script src="<?php echo $this->basePath('/js/excanvas.js'); ?>"></script>
<![endif]-->

<script src="<?php echo $this->basePath('/js/jquery-ui.custom.js'); ?>"></script>
<script src="<?php echo $this->basePath('/js/jquery.ui.touch-punch.js'); ?>"></script>

<!--[if lte IE 8]>
<script src="<?php echo $this->basePath('/js/excanvas.js'); ?>"></script>
<![endif]-->

<script src="<?php echo $this->basePath('/js/jquery-ui.custom.js'); ?>"></script>
<script src="<?php echo $this->basePath('/js/jquery.ui.touch-punch.js'); ?>"></script>


<!-- ace scripts -->
<script src="<?php echo $this->basePath('/js/ace.js'); ?>"></script>

<!-- ace settings handler -->
<script src="<?php echo $this->basePath('/js/ace-extra.js'); ?>"></script>

<script src="<?php echo $this->basePath('/assets/datatable/media/js/jquery.dataTables.js'); ?>"></script>
<script src="<?php echo $this->basePath('/assets/datatable/media/js/jquery.dataTables.bootstrap.js'); ?>"></script>
<script
    src="<?php echo $this->basePath('/assets/datatable/extensions/TableTools/js/dataTables.tableTools.js'); ?>"></script>
<script
    src="<?php echo $this->basePath('/assets/datatable/extensions/ColVis/js/dataTables.colVis.min.js'); ?>"></script>
<script
    src="<?php echo $this->basePath('/assets/datatable/extensions/ColReorder/js/dataTables.colReorder.min.js'); ?>"></script>
<script
    src="<?php echo $this->basePath('/assets/datatable/extensions/TableTools/js/dataTables.tableTools.min.js'); ?>"></script>

<script src="<?php echo $this->basePath('/assets/bootbox/bootbox.js'); ?>"></script>
<script src="<?php echo $this->basePath('/assets/select2/select2.js'); ?>"></script>

<script src="<?php echo $this->basePath('/js/bootstrap-notify.js'); ?>"></script>
<script src="<?php echo $this->basePath('/assets/inputmask/jquery.inputmask.js'); ?>"></script>
<script src="<?php echo $this->basePath('/assets/inputlimiter/jquery.inputlimiter.1.3.1.js'); ?>"></script>

<script src="<?php echo $this->basePath('/js/util/diversos.js'); ?>"></script>
<script src="<?php echo $this->basePath('/js/util/datatable.js'); ?>"></script>

<script src="<?php echo $this->basePath('/js/cjf.js'); ?>"></script>


<?php echo $this->headScript(); ?>

<script> var BASE_PATH = "<?php echo $this->basePath(); ?>/"; </script>

<!-- inline scripts related to this page -->