<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Sisdo'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('css/app.css'))
            ->prependStylesheet($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'))
            ->prependStylesheet($this->basePath('plugins/daterangepicker/daterangepicker-bs3.css'))
            ->prependStylesheet($this->basePath('plugins/datepicker/datepicker3.css'))
            ->prependStylesheet($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.css'))
            ->prependStylesheet($this->basePath('plugins/morris/morris.css'))
            ->prependStylesheet($this->basePath('plugins/iCheck/flat/blue.css'))
            ->prependStylesheet($this->basePath('css/skins/_all-skins.min.css'))
            ->prependStylesheet($this->basePath('css/AdminLTE.css'))
            ->prependStylesheet($this->basePath('js/bootstrap-rating/css/star-rating.min.css'))
            ->prependStylesheet($this->basePath('css/jquery-ui.structure.css'))
            ->prependStylesheet($this->basePath('css/jquery-ui.theme.css'))
            ->prependStylesheet($this->basePath('css/jquery-ui.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('/jqgrid/css/ui.jqgrid-bootstrap.css')) ?>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">


        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/sisdo/sisdo.js'))
            // ->prependFile($this->basePath('js/demo.js'))
            ->prependFile($this->basePath('js/pages/dashboard.js'))
            ->prependFile($this->basePath('js/app.js'))
            ->prependFile($this->basePath('plugins/fastclick/fastclick.min.js'))
            ->prependFile($this->basePath('plugins/slimScroll/jquery.slimscroll.min.js'))
            ->prependFile($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'))
            ->prependFile($this->basePath('plugins/daterangepicker/daterangepicker.js'))
            ->prependFile($this->basePath('plugins/knob/jquery.knob.js'))
            ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-world-mill-en.js'))
            ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'))
            ->prependFile($this->basePath('plugins/sparkline/jquery.sparkline.min.js'))
            ->prependFile($this->basePath('plugins/morris/morris.min.js'))
            ->prependFile($this->basePath('js/bootstrap-rating/js/star-rating.min.js'))
            ->prependFile($this->basePath('js/jquery.maskedinput.min.js'))
            ->prependFile($this->basePath('js/bootbox.min.js'))
            ->prependFile($this->basePath('js/bootstrap-notify.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('/jqgrid/js/jquery.jqGrid.min.js'))
            ->prependFile($this->basePath('/jqgrid/js/i18n/grid.locale-pt-br.js'))
            ->prependFile($this->basePath('js/jquery-ui.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"> <b>Sis</b>Doar</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">

            <div class="main-content">
                <div class="row">
                    <div class="col-xs-12">
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </div>
            <hr>
            <footer>

            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>

    <script>
        function showMessages(text, type) {

            if (type == undefined) {
                type = 'info';
            }

            $.notify({message: text}, {type: type, z_index: 2050});
        }

        function jsonResult(result) {
            if (result.status) {
                showMessages(result.message.message, result.message.status)
            } else {
                showMessages(result.error, 'danger');
                return false;
            }
        }

        <?php // echo $this->FlashMessengerHelper(); ?>

        /*$(document).ready(function () {
            showMessages('teste');
        })*/
    </script>


</html>
