<?php echo $this->doctype(); ?>

<html lang="pt-br" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Sisdo'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
         ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'))
        ->prependStylesheet($this->basePath('plugins/daterangepicker/daterangepicker-bs3.css'))
        ->prependStylesheet($this->basePath('plugins/datepicker/datepicker3.css'))
        ->prependStylesheet($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.css'))
        ->prependStylesheet($this->basePath('plugins/morris/morris.css'))
        ->prependStylesheet($this->basePath('plugins/iCheck/flat/blue.css'))
        ->prependStylesheet($this->basePath('css/skins/_all-skins.min.css'))
        ->prependStylesheet($this->basePath('css/AdminLTE.css'))
        ->prependStylesheet($this->basePath('js/bootstrap-rating/css/star-rating.min.css'))
        ->prependStylesheet($this->basePath('css/jquery-ui.structure.css'))
        ->prependStylesheet($this->basePath('css/jquery-ui.theme.css'))
        ->prependStylesheet($this->basePath('css/jquery-ui.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('/jqgrid/css/ui.jqgrid-bootstrap.css')) ?>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">


    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/sisdo/sisdo.js'))
       // ->prependFile($this->basePath('js/demo.js'))
        ->prependFile($this->basePath('js/pages/dashboard.js'))
        ->prependFile($this->basePath('js/app.js'))
        ->prependFile($this->basePath('plugins/fastclick/fastclick.min.js'))
        ->prependFile($this->basePath('plugins/slimScroll/jquery.slimscroll.min.js'))
        ->prependFile($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'))
        ->prependFile($this->basePath('plugins/daterangepicker/daterangepicker.js'))
        ->prependFile($this->basePath('plugins/knob/jquery.knob.js'))
        ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-world-mill-en.js'))
        ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'))
        ->prependFile($this->basePath('plugins/sparkline/jquery.sparkline.min.js'))
        ->prependFile($this->basePath('plugins/morris/morris.min.js'))
        ->prependFile($this->basePath('js/bootstrap-rating/js/star-rating.min.js'))
        ->prependFile($this->basePath('js/jquery.maskedinput.min.js'))
        ->prependFile($this->basePath('js/bootbox.min.js'))
        ->prependFile($this->basePath('js/bootstrap-notify.min.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('/jqgrid/js/jquery.jqGrid.min.js'))
        ->prependFile($this->basePath('/jqgrid/js/i18n/grid.locale-pt-br.js'))
        ->prependFile($this->basePath('js/jquery-ui.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<?php
$meusDados = '';
$user = $this->nameUser();
?>
<body class="hold-transition skin-red-light sidebar-mini">
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="/" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><img src="/img/logo.png" /></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Sis</b>DOAR</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <div class="navbar-custom-menu" style="height: 10px">
                <ul class="nav navbar-nav">
                    <!-- Messages: style can be found in dropdown.less-->
                    <li class="dropdown messages-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-envelope-o"></i>
                            <span class="label label-success">4</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">Você tem 4 mensagens</li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    <li><!-- start message -->
                                        <a href="#">
                                            <div class="pull-left">
                                                <img src="/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                                            </div>
                                            <h4>
                                                Support Team
                                                <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                            </h4>
                                            <p>Why not buy a new awesome theme?</p>
                                        </a>
                                    </li><!-- end message -->
                                    <li>
                                        <a href="#">
                                            <div class="pull-left">
                                                <img src="/img/user3-128x128.jpg" class="img-circle" alt="User Image">
                                            </div>
                                            <h4>
                                                AdminLTE Design Team
                                                <small><i class="fa fa-clock-o"></i> 2 hours</small>
                                            </h4>
                                            <p>Why not buy a new awesome theme?</p>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <div class="pull-left">
                                                <img src="/img/user4-128x128.jpg" class="img-circle" alt="User Image">
                                            </div>
                                            <h4>
                                                Developers
                                                <small><i class="fa fa-clock-o"></i> Today</small>
                                            </h4>
                                            <p>Why not buy a new awesome theme?</p>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <div class="pull-left">
                                                <img src="/img/user3-128x128.jpg" class="img-circle" alt="User Image">
                                            </div>
                                            <h4>
                                                Sales Department
                                                <small><i class="fa fa-clock-o"></i> Yesterday</small>
                                            </h4>
                                            <p>Why not buy a new awesome theme?</p>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <div class="pull-left">
                                                <img src="/img/user4-128x128.jpg" class="img-circle" alt="User Image">
                                            </div>
                                            <h4>
                                                Reviewers
                                                <small><i class="fa fa-clock-o"></i> 2 days</small>
                                            </h4>
                                            <p>Why not buy a new awesome theme?</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="footer"><a href="#">See All Messages</a></li>
                        </ul>
                    </li>
                    <!-- Notifications: style can be found in dropdown.less -->
                    <li class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bell-o"></i>
                            <span class="label label-warning">10</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">You have 10 notifications</li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the page and may cause design problems
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-users text-red"></i> 5 new members joined
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-user text-red"></i> You changed your username
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="footer"><a href="#">Ver Todas</a></li>
                        </ul>
                    </li>

                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="<?php echo $user['picture'] ?>" class="user-image" alt="User Image">
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="<?php echo $user['picture'] ?>" class="img-circle" alt="User Image">
                                <p>
                                    <?php echo $user['name'];?>
                                    <small><?php echo $user['dateMember'];?></small>
                                </p>
                            </li>
                            <!-- Menu Body -->
                            <li class="user-body">
                                <div class="col-xs-4 text-center">
                                    <a href="#">Seguidores</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Transações</a>
                                </div>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="/instituicao/pagina/<?php echo $user['id'] ?>" class="btn btn-default btn-flat">Perfil</a>
                                </div>
                                <div class="pull-right">
                                    <a href="/user/logout" class="btn btn-default btn-flat">Logout</a>
                                </div>
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="<?php echo $user['picture'] ?>" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p><?php echo $user['name'];?></p>
                    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                </div>
            </div>
            <!-- search form -->
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Pesquisar...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <?php

            $link = $_SERVER['REQUEST_URI'];

            if ($user['profile'] == \Application\Constants\ProfileConst::FLAG_PROFILE_INSTITUTION) {
                $meusDados = '/instituicao';
                echo $this->menuLateralHelper()->getMenuInstitution($link);
            } else {
                $meusDados = '/pessoa';
                echo $this->menuLateralHelper()->getMenuPerson();
            }
            ?>

        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                <?php echo $this->title ?>
            </h1>
            <?php echo $this->partial("partials/breadcrumb.phtml", array('layout' => $this->layout())); ?>

        </section>

        <!-- Main content -->
        <section class="content">
            <?php echo $this->content; ?>
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
    <footer class="main-footer">
        <strong>Copyright &copy; <?php $data = new DateTime('now'); echo $data->format('Y'); ?> <a href="/">Sisdoar</a>.</strong> Todos os direitos reservados.
    </footer>

    <!-- Add the sidebar's background. This div must be placed
         immediately after the control sidebar -->
    <div class="control-sidebar-bg"></div>
</div><!-- ./wrapper -->
</body>

<script>
    $.widget.bridge('uibutton', $.ui.button);

    function showMessages(text, type) {

        if (type == undefined) {
            type = 'info';
        }
        $.notify({message: text}, {type: type, z_index: 2050});
    }

    function jsonResult(result) {
        if (result.status) {
            showMessages(result.message.message, result.message.status)
        } else {
            showMessages(result.error, 'danger');
            return false;
        }
    }

    $(function(){

        $('#srch-term').autocomplete({

            minLength: 1,
            source: function (request, response) {

                var DTO = { "term": request.term };
                sisdoAjax('/instituicao/getInstituctionAutoComplete','GET',DTO,
                    function (data) {

                        var instituicoes = [];
                        $.each( data, function( key, value ) {
                            instituicoes.push(value);
                        });
                        return response(instituicoes);
                    }
                    ,null,{global:false});
            }
        });
    });

</script>

<?php
$flash = $this->flashMessenger();

if ($flash->hasCurrentSuccessMessages()) {

    $message = $flash->render('success');
    echo "<script>showMessages(`{$message}`, 'success');</script>";
}
if ($flash->hasCurrentErrorMessages()) {

    $message = $flash->render('error');
    echo "<script>showMessages(`{$message}`, 'danger');</script>";
}
if ($flash->hasCurrentInfoMessages()) {
    $message = $flash->render('info');
    echo "<script>showMessages(`{$message}`, 'info');</script>";
}
if ($flash->hasCurrentWarningMessages()) {
    $message = $flash->render('warning');
    echo "<script>showMessages(`{$message}`, 'warning');</script>";
}

?>


</html>
