<?php

echo $this->form(null, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_INLINE)->openTag($this->form);
$this->form->prepare();

?>



<?php echo $this->formRow($this->form->get(\Sisdo\Constants\TransactionConst::FLD_ID_TRANSACTION)); ?>
<?php echo $this->formRow($this->form->get(\Sisdo\Constants\TransactionConst::FLD_INSTITUTION_USER)); ?>
<?php echo $this->formRow($this->form->get(\Sisdo\Constants\TransactionConst::FLD_PRODUTO)); ?>
<?php echo $this->formRow($this->form->get(\Sisdo\Constants\TransactionConst::FLD_PERSON_USER)); ?>
<?php echo $this->formRow($this->form->get(\Sisdo\Constants\TransactionConst::FLD_STATUS)); ?>
<?php echo $this->formRow($this->form->get(\Sisdo\Constants\TransactionConst::FLD_SHIPPING_METHOD)); ?>
<?php echo $this->formRow($this->form->get(\Sisdo\Constants\TransactionConst::FLD_QUANTIFY)); ?><br>
<?php echo $this->formRow($this->form->get(\Sisdo\Constants\TransactionConst::FLD_START_DATE)); ?>
<?php echo $this->formRow($this->form->get(\Sisdo\Constants\TransactionConst::FLD_END_DATE)); ?>


<div class="row botoesacao center-block">
    <?php echo $this->formButton($this->form->get('btn_ver_mensagens')); ?>
    <?php echo $this->formButton($this->form->get('btn_finalizar_doacao')); ?>
    <?php echo $this->formButton($this->form->get('btn_rejeitar')); ?>
</div>

<?php echo $this->form()->closeTag(); ?>


<div class="box box-primary direct-chat direct-chat-primary center-block" style=" margin-top: 2%">
    <div class="box-header with-border">
        <h3 class="box-title">Conversa</h3>
        <div class="box-tools pull-right">
            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
        </div>
    </div><!-- /.box-header -->
    <div class="box-body">

<?php
foreach($this->conversa as $mensagem){
    if($mensagem instanceof \Sisdo\Entity\Message) {
        if($mensagem->getIdUser()->getInstituicao()){
            echo "<div class='direct-chat-msg'>
                            <div class='direct-chat-info clearfix'>
                                <span class='direct-chat-name pull-left'>{$mensagem->getIdUser()->getInstituicao()->getFancyName()}</span>
                                <span class='direct-chat-timestamp pull-right'>{$mensagem->getDate()->format('d/m/Y')}</span>
                            </div><!-- /.direct-chat-info -->
                            <img class='direct-chat-img' src='{$mensagem->getIdUser()->getInstituicao()->getPicture()}' alt='message user image'><!-- /.direct-chat-img -->
                            <div class='direct-chat-text'>
                                    {$mensagem->getMessage()}
                            </div><!-- /.direct-chat-text -->
                </div><!-- /.direct-chat-msg -->";
        }else{
            echo "<div class='direct-chat-msg right'>
                            <div class='direct-chat-info clearfix'>
                                <span class='direct-chat-name pull-right'>{$mensagem->getIdUser()->getPerson()->getName()}</span>
                                <span class='direct-chat-timestamp pull-left'>{$mensagem->getDate()->format('d/m/Y')}</span>
                            </div><!-- /.direct-chat-info -->
                            <img class='direct-chat-img' src='{$mensagem->getIdUser()->getPerson()->getPicture()}' alt='message user image'><!-- /.direct-chat-img -->
                            <div class='direct-chat-text'>
                                    {$mensagem->getMessage()}
                            </div><!-- /.direct-chat-text -->
                </div><!-- /.direct-chat-msg -->";
        }
    }
}
?>
</div>



    <div class="box-footer">
        <?php echo $this->form(null, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL)->openTag($this->formMessage);
        $this->formMessage->prepare(); ?>
            <div class="input-group">
                <?php echo $this->formElement($this->formMessage->get(\Sisdo\Constants\MessageConst::FLD_USER)); ?>
                <?php echo $this->formElement($this->formMessage->get(\Sisdo\Constants\MessageConst::FLD_TRANSACAO)); ?>

                <?php echo $this->formElement($this->formMessage->get(\Sisdo\Constants\MessageConst::FLD_MENSAGEM)); ?>
                  <span class="input-group-btn">
                        <?php echo $this->formButton($this->formMessage->get('btnEnviar')); ?>
                  </span>
            </div>
            <?php echo $this->form()->closeTag(); ?>
    </div><!-- /.box-footer-->
</div>


<script src="/js/sisdo/transacao.js"></script>
