<?php echo $this->doctype(); ?>

<html lang="pt-br" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Sisdo'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/template-style.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('js/bootstrap-rating/css/star-rating.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('/jqgrid/css/ui.jqgrid-bootstrap.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/sisdo/sisdo.js'))
        ->prependFile($this->basePath('js/bootstrap-rating/js/star-rating.min.js'))
        ->prependFile($this->basePath('js/jquery.maskedinput.min.js'))
        ->prependFile($this->basePath('js/bootbox.min.js'))
        ->prependFile($this->basePath('js/bootstrap-notify.min.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('/jqgrid/js/jquery.jqGrid.min.js'))
        ->prependFile($this->basePath('/jqgrid/js/i18n/grid.locale-pt-br.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

</head>
<body>
<div class="wrapper">
    <div class="box">
        <div class="row row-offcanvas row-offcanvas-left">


            <!-- sidebar -->
            <?php
            $meusDados = '';
            $user = $this->nameUser();

            $link = $_SERVER['REQUEST_URI'];

            if ($user['profile'] == \Application\Constants\ProfileConst::FLAG_PROFILE_INSTITUTION) {
                $meusDados = '/instituicao';
                echo $this->menuLateralHelper()->getMenuInstitution($link);
            } else {
                $meusDados = '/pessoa';
                echo $this->menuLateralHelper()->getMenuPerson();
            }
            ?>
            <!-- /sidebar -->

            <!-- main right col -->
            <div class="column col-sm-10 col-xs-11" id="main">
                <!-- top nav -->
                <div class="navbar navbar-blue navbar-static-top">
                    <div class="navbar-header">
                        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="/" class=""><img style="margin-left: 10px;width: 100px;height: 50px;" src="/img/logo.png"></a>
                    </div>
                    <nav class="collapse navbar-collapse" role="navigation">
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="/"><i class="glyphicon glyphicon-home"></i> Inicio</a>
                            </li>
                            <li>
                                <a href="#"><i class="glyphicon glyphicon-globe"></i> Notificacoes</a>
                            </li>
                            <li>
                                <a href="/ajuda"><i class="glyphicon glyphicon-info-sign"></i> Faq</a>
                            </li>

                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="margin-right: 40px"><i
                                        style="font-size: 20px"
                                        class="fa fa-user"></i> <?php echo $this->nameUser()['name'] ?></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $meusDados ?>"><i class="fa fa-user"></i> Meus Dados</a>
                                        </li>
                                        <li><a href="/user/logout"><i class="fa fa-sign-out"></i> Logout</a></li>
                                    </ul>
                            </li>
                        </ul>
                    </nav>
                </div><!-- /top nav -->
                <div class="padding">
                    <div class="full col-sm-9">
                        <?php echo $this->content; ?>
                    </div>

                    <!-- <footer id="footer" class="text-center">
                          <div class="col-sm-11" style="margin-top: 30px">
                              <p>
                                  <a href="#" class="text-center">Copyright PA 2015</a>
                              </p>
                          </div>
                      </footer>-->
                </div>
            </div><!-- /main -->

        </div>
    </div>

    <div id="preloading">
        <div id="loading">&nbsp;</div>
    </div>


</div>



</body>

<script>
    function showMessages(text, type) {

        if (type == undefined) {
            type = 'info';
        }
        $.notify({message: text}, {type: type, z_index: 2050});
    }

    function jsonResult(result) {
        if (result.status) {
            showMessages(result.message.message, result.message.status)
        } else {
            showMessages(result.error, 'danger');
            return false;
        }
    }

</script>

<?php
$flash = $this->flashMessenger();

if ($flash->hasCurrentSuccessMessages()) {

    $message = $flash->render('success');
    echo "<script>showMessages(`{$message}`, 'success');</script>";
}
if ($flash->hasCurrentErrorMessages()) {

    $message = $flash->render('error');
    echo "<script>showMessages(`{$message}`, 'danger');</script>";
}
if ($flash->hasCurrentInfoMessages()) {
    $message = $flash->render('info');
    echo "<script>showMessages(`{$message}`, 'info');</script>";
}
if ($flash->hasCurrentWarningMessages()) {
    $message = $flash->render('warning');
    echo "<script>showMessages(`{$message}`, 'warning');</script>";
}

?>

</html>
