<?php

/** @var \Sisdo\Entity\Institution $institution */
$institution = $this->institution;
$userInstitution = $institution->getUserId();

?>


<section class="content">

    <div class="row">
        <div class="col-md-3">

            <!-- Profile Image -->
            <div class="box box-primary">
                <div class="box-body box-profile">
                    <img class="profile-user-img img-responsive img-circle" src="<?php echo $institution->getPicture() ?>" alt="User profile picture">
                    <h3 class="profile-username text-center"><?php echo $institution->getFancyName(); ?></h3>

                    <ul class="list-group list-group-unbordered">
                        <li class="list-group-item">
                            <strong>Email: </strong><?php echo $userInstitution->getEmail(); ?>
                        </li>
                        <li class="list-group-item">
                            <strong>CNPJ: </strong><?php echo $institution->getCnpj(); ?>
                        </li>
                        <li class="list-group-item">
                            <strong>Ramo: </strong><?php echo \Sisdo\Entity\RamoInstituicao::getRamoById($institution->getBranch()); ?>
                        </li>
                    </ul>

                    <a href="/relationship/seguir/<?php echo $institution->getId() ?>"
                       class="btn <?php echo !$this->seguindo ? 'btn-primary' : 'btn-danger' ?> btn-block"><b>
                            <?php echo !$this->seguindo ? 'Seguir' : 'Parar de Seguir' ?></b></a>
                </div><!-- /.box-body -->
            </div><!-- /.box -->

            <!-- About Me Box -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Sobre</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <p class="text-muted">
                        <?php echo $institution->getAbout() ?>
                    </p>

                    <hr>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div><!-- /.col -->
        <div class="col-md-9">
            <h4>Doações</h4>
            <?php
            /** @var \Sisdo\Entity\Product $produto */
            foreach($this->produtos as $produto){
                echo <<<DOC
                <div class="col-sm-4">
                    <div class="thumbnail">
                      <div class="caption">
                        <h5><strong>{$produto->getTitle()}</strong></h5>
                            <p>{$produto->getDescription()}</p>
                        <p><a href="/transacao/doar" class="btn btn-primary">Doar</a></p>
                      </div>
                    </div>
                </div>
DOC;
            }

            ?>
        </div><!-- /.col -->
    </div><!-- /.row -->

</section><!-- /.content -->
</div><!-- /.content-wrapper -->

