<h4><i style="color: #d9cd0f;" class="glyphicon glyphicon-info-sign"></i> Pesquisar Instituicoes</h4>
<hr>

<?php
echo $this->form(null, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_INLINE)->openTag($this->formSearch);
$this->formSearch->prepare();
?>

<?php echo $this->formRow($this->formSearch->get(\Sisdo\Constants\InstitutionConst::FLD_FANCY_NAME)); ?>
<?php echo $this->formRow($this->formSearch->get(\Sisdo\Constants\AdressConst::FLD_UF)); ?>

<div class="form-group " style="margin-top: 2%;">
    <?php echo $this->formButton($this->formSearch->get('btn_search')); ?>
</div>

<?php echo $this->form()->closeTag(); ?>



<div class="row" style="margin-top: 4%;">
    <?php

    /** @var \Sisdo\Entity\Institution $instituicao */
    foreach ($this->institutions as $instituicao) {
        //var_dump($instituicao);die;

        /** @var \Application\Entity\User $userInstituicao */
        // $userInstituicao = $instituicao->getUserId();

        echo <<<DOC

        <div class="col-md-4">
              <!-- Widget: user widget style 1 -->
              <div class="box box-widget widget-user">
                <!-- Add the bg color to the header using any of the bg-* classes -->
                <div class="widget-user-header bg-aqua-active">
                  <h3 class="widget-user-username">{$instituicao->getFancyName()}</h3>
                </div>
                <div class="widget-user-image">
                    <img style='width:90px' class='img-circle' src="{$instituicao->getPicture()}" data-holder-rendered="true" style="height: 200px; width: 100%; display: block;">
                </div>
                <div class="box-footer">
                  <div class="row">
                    <div class="col-sm-4 border-right">
                      <div class="description-block">
                        <h5 class="description-header">3,200</h5>
                        <span class="description-text">Seguidores</span>
                      </div><!-- /.description-block -->
                    </div><!-- /.col -->
                    <div class="col-sm-4 border-right">
                      <div class="description-block">
                        <button class="btn btn-primary description-text">Seguir</button>
                      </div><!-- /.description-block -->
                    </div><!-- /.col -->
                    <div class="col-sm-4">
                      <div class="description-block">
                        <a href='/instituicao/pagina/{$instituicao->getUserId()->getId()}' class="btn btn-default description-text">Ver Mais</a>
                      </div><!-- /.description-block -->
                    </div><!-- /.col -->
                  </div><!-- /.row -->
                </div>
              </div><!-- /.widget-user -->
            </div>


DOC;
    }
    ?>
</div>