<div class="row">
    <div class="col-xs-6 col-lg-4">
        <h2><b>Produtos</b></h2>

        <p>Cadastre e gerencie seus produtos</p>
        <a href="/produto">Ir para produtos</a>
    </div>
    <!--/.col-xs-6.col-lg-4-->
    <div class="col-xs-6 col-lg-4">
        <h2><b>Estoque</b></h2>

        <p>Gerencie seu estoque</p>
        <a href="/estoque">Ir para estoque</a>
    </div>
    <!--/.col-xs-6.col-lg-4-->
    <div class="col-xs-6 col-lg-4">
        <h2><b>Fornecedor</b></h2>

        <p>Cadastre e gerencie seus fornecedores</p>
        <a href="/fornecedor">Ir para fornecedores</a>
    </div>

    <div class="col-xs-6 col-lg-4">
        <h2><b>Pedidos</b></h2>

        <p>Cadastre pedidos e seus itens</p>
        <a href="/pedido">Ir para pedidos</a>
    </div>

    <div class="col-xs-6 col-lg-4">
        <h2><b>Notas Fiscais</b></h2>

        <p>Consultas as notas fiscais geradas</p>
        <a href="/nota-fiscal">Ir para notas fiscais</a>
    </div>

</div>